services:
  postgres:
    image: postgres:15-alpine
    container_name: pz8-postgres
    environment:
      POSTGRES_USER:     tasks_user
      POSTGRES_PASSWORD: tasks_pass
      POSTGRES_DB:       tasks_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasks_user -d tasks_db"]
      interval: 3s
      timeout: 3s
      retries: 10
    networks: [app-network]

  auth:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.auth
    container_name: pz8-auth
    environment:
      AUTH_PORT: "8081"
    networks: [app-network]

  tasks:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.tasks
    container_name: pz8-tasks
    environment:
      TASKS_PORT:    "8082"
      AUTH_BASE_URL: "http://auth:8081"
      DB_HOST:       postgres
      DB_PORT:       "5432"
      DB_USER:       tasks_user
      DB_PASSWORD:   tasks_pass
      DB_NAME:       tasks_db
      DB_SSLMODE:    disable
    depends_on:
      postgres:
        condition: service_healthy
      auth:
        condition: service_started
    networks: [app-network]

  nginx:
    image: nginx:1.27-alpine
    container_name: pz8-nginx
    ports:
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./tls:/etc/nginx/tls:ro
    depends_on: [tasks]
    networks: [app-network]

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
